"use client";
import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/lib/supabase";
type C={id:string;first_name:string;last_name:string;email?:string;phone?:string;current_title?:string;current_company?:string;status:string;source?:string;city?:string;state?:string;skills?:string[];overall_score?:number;english_rate?:number;experience_years?:number;resume_text?:string;cover_letter?:string;screening_responses?:any;application_answers?:any;interview_notes?:string;notes?:string;video_url?:string;ai_recommendation?:string;ai_analysis?:any;created_at:string;};
const SC:Record<string,string>={new:"bg-blue-100 text-blue-800",contacted:"bg-yellow-100 text-yellow-800",screening:"bg-indigo-100 text-indigo-800",interviewing:"bg-purple-100 text-purple-800",hired:"bg-green-100 text-green-800",rejected:"bg-red-100 text-red-800",on_bench:"bg-sky-100 text-sky-800",active:"bg-green-100 text-green-800",open:"bg-green-100 text-green-800",on_hold:"bg-yellow-100 text-yellow-800",closed:"bg-gray-100 text-gray-700"};
function B({s}:{s:string}){return <span className={`px-2 py-0.5 rounded-full text-xs font-semibold capitalize ${SC[s]||"bg-gray-100 text-gray-700"}`}>{(s||"").replace(/_/g," ")}</span>;}
function Av({n,sz="w-8 h-8 text-xs"}:{n:string;sz?:string}){return <div className={`${sz} rounded-full bg-blue-50 text-blue-700 flex items-center justify-center font-semibold shrink-0`}>{(n||"?").split(" ").map(w=>w[0]).join("").slice(0,2).toUpperCase()}</div>;}

function Dash({nav}:{nav:(p:string,d?:any)=>void}){
const[d,setD]=useState<any>(null);const[rec,setRec]=useState<C[]>([]);
useEffect(()=>{(async()=>{const[{data:ca},{data:jo},{data:ap},{data:cl},{data:st}]=await Promise.all([supabase.from("candidates").select("id,status,source"),supabase.from("jobs").select("id,status"),supabase.from("applications").select("id"),supabase.from("clients").select("id,status"),supabase.from("pipeline_stages").select("*").order("sort_order")]);const{data:r}=await supabase.from("candidates").select("*").order("created_at",{ascending:false}).limit(10);setD({t:ca?.length||0,oj:jo?.filter((j:any)=>j.status==="open").length||0,ap:ap?.length||0,ac:cl?.filter((c:any)=>c.status==="active").length||0,sb:(ca||[]).reduce((a:any,c:any)=>{a[c.status]=(a[c.status]||0)+1;return a;},{}),src:(ca||[]).reduce((a:any,c:any)=>{a[c.source||"unknown"]=(a[c.source||"unknown"]||0)+1;return a;},{}),st:st||[]});setRec(r||[]);})();},[]);
if(!d)return<div className="py-20 text-center text-gray-400">Loading...</div>;
return<div>
<div className="flex justify-between items-center mb-6"><h1 className="text-xl font-semibold">Dashboard</h1></div>
<div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">{[["Candidates",d.t],["Open jobs",d.oj],["Applications",d.ap],["Clients",d.ac]].map(([l,v])=><div key={l as string} className="bg-white rounded-xl border p-4"><div className="text-[10px] text-gray-400 uppercase tracking-wider mb-1">{l}</div><div className="text-2xl font-semibold">{v}</div></div>)}</div>
<div className="grid md:grid-cols-2 gap-4 mb-6">
<div className="bg-white rounded-xl border p-4"><h3 className="text-sm text-gray-500 mb-3">By status</h3>{Object.entries(d.sb).sort((a:any,b:any)=>b[1]-a[1]).map(([s,c]:any)=><div key={s} className="flex items-center gap-2 mb-1"><B s={s}/><div className="flex-1 h-1.5 bg-gray-100 rounded-full"><div className="h-full bg-blue-400 rounded-full"style={{width:`${(c/d.t)*100}%`}}/></div><span className="text-xs w-7 text-right">{c}</span></div>)}</div>
<div className="bg-white rounded-xl border p-4"><h3 className="text-sm text-gray-500 mb-3">By source</h3>{Object.entries(d.src).sort((a:any,b:any)=>b[1]-a[1]).slice(0,6).map(([s,c]:any)=><div key={s} className="flex items-center gap-2 mb-2"><span className="text-xs text-gray-400 w-20 capitalize truncate">{s}</span><div className="flex-1 h-2 bg-gray-100 rounded-full"><div className="h-full bg-blue-500 rounded-full"style={{width:`${(c/Math.max(...Object.values(d.src)as number[]))*100}%`}}/></div><span className="text-xs w-7 text-right">{c}</span></div>)}</div>
</div>
<div className="bg-white rounded-xl border p-4 mb-6"><h3 className="text-sm text-gray-500 mb-3">Pipeline</h3><div className="flex gap-1">{d.st.map((s:any)=><div key={s.id} className="flex-1 text-center py-2 rounded-lg"style={{background:s.color+"18",border:`1px solid ${s.color}30`}}><div className="text-[9px] font-semibold"style={{color:s.color}}>{s.name}</div></div>)}</div></div>
<h3 className="text-sm text-gray-500 mb-3">Recent candidates</h3>
<div className="bg-white rounded-xl border divide-y">{rec.map(c=><div key={c.id} onClick={()=>nav("det",{id:c.id})} className="flex items-center gap-3 px-4 py-3 cursor-pointer hover:bg-gray-50"><Av n={`${c.first_name} ${c.last_name}`}/><div className="flex-1 min-w-0"><div className="text-sm font-medium truncate">{c.first_name} {c.last_name}</div><div className="text-xs text-gray-400 truncate">{c.current_title||c.email||""}</div></div>{c.screening_responses&&<span className="text-[9px] text-blue-600">responses</span>}<B s={c.status}/></div>)}</div>
</div>;}

function Cands({nav}:{nav:(p:string,d?:any)=>void}){
const[cs,setCs]=useState<C[]>([]);const[q,setQ]=useState("");const[f,setF]=useState("all");const[pg,setPg]=useState(0);const[tot,setTot]=useState(0);
useEffect(()=>{(async()=>{let qr=supabase.from("candidates").select("*",{count:"exact"});if(q)qr=qr.or(`first_name.ilike.%${q}%,last_name.ilike.%${q}%,email.ilike.%${q}%,current_title.ilike.%${q}%`);if(f!=="all")qr=qr.eq("status",f);const{data,count}=await qr.order("created_at",{ascending:false}).range(pg*25,(pg+1)*25-1);setCs(data||[]);setTot(count||0);})();},[q,f,pg]);
return<div>
<h1 className="text-xl font-semibold mb-4">Candidates ({tot})</h1>
<div className="flex gap-2 mb-4"><input value={q} onChange={e=>{setQ(e.target.value);setPg(0);}} placeholder="Search..." className="flex-1 px-3 py-2 border rounded-lg text-sm"/><select value={f} onChange={e=>{setF(e.target.value);setPg(0);}} className="px-3 py-2 border rounded-lg text-sm"><option value="all">All</option>{["new","contacted","screening","interviewing","hired","rejected","on_bench"].map(s=><option key={s} value={s}>{s.replace(/_/g," ")}</option>)}</select></div>
<div className="bg-white rounded-xl border overflow-hidden"><table className="w-full text-sm"><thead><tr className="border-b text-left">{["Name","Title","Status","Source","Responses","Date"].map(h=><th key={h} className="px-3 py-2 text-[10px] font-semibold text-gray-400 uppercase">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-50">{cs.map(c=><tr key={c.id} onClick={()=>nav("det",{id:c.id})} className="cursor-pointer hover:bg-gray-50"><td className="px-3 py-2"><div className="flex items-center gap-2"><Av n={`${c.first_name} ${c.last_name}`} sz="w-6 h-6 text-[9px]"/><div><div className="font-medium">{c.first_name} {c.last_name}</div><div className="text-[10px] text-gray-400">{c.email||""}</div></div></div></td><td className="px-3 py-2 text-gray-500">{c.current_title||""}</td><td className="px-3 py-2"><B s={c.status}/></td><td className="px-3 py-2 text-gray-400 capitalize text-xs">{c.source||""}</td><td className="px-3 py-2">{(c.screening_responses||c.application_answers)?<span className="text-[9px] px-1.5 py-0.5 bg-green-50 text-green-700 rounded-full">Yes</span>:""}</td><td className="px-3 py-2 text-[10px] text-gray-400">{new Date(c.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>
<div className="flex justify-between px-3 py-2 border-t text-xs text-gray-400"><span>{pg*25+1}-{Math.min((pg+1)*25,tot)} of {tot}</span><div className="flex gap-1"><button disabled={pg===0} onClick={()=>setPg(p=>p-1)} className="px-2 py-1 border rounded disabled:opacity-30">Prev</button><button disabled={(pg+1)*25>=tot} onClick={()=>setPg(p=>p+1)} className="px-2 py-1 border rounded disabled:opacity-30">Next</button></div></div></div>
</div>;}

function Det({nav,pr}:{nav:(p:string,d?:any)=>void;pr:any}){
const[c,setC]=useState<C|null>(null);const[tab,setTab]=useState("overview");
useEffect(()=>{supabase.from("candidates").select("*").eq("id",pr.id).single().then(({data})=>setC(data));},[pr.id]);
if(!c)return<div className="py-20 text-center text-gray-400">Loading...</div>;
return<div>
<button onClick={()=>nav("cands")} className="text-sm text-gray-400 mb-4 block">&larr; Back</button>
<div className="bg-white rounded-xl border p-5 mb-4"><div className="flex gap-4"><Av n={`${c.first_name} ${c.last_name}`} sz="w-14 h-14 text-xl"/><div className="flex-1"><div className="flex items-center gap-3 mb-1 flex-wrap"><h1 className="text-lg font-semibold">{c.first_name} {c.last_name}</h1><B s={c.status}/>{c.ai_recommendation&&<span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${c.ai_recommendation==="ADVANCE"?"bg-green-100 text-green-700":"bg-yellow-100 text-yellow-700"}`}>{c.ai_recommendation}</span>}</div><div className="text-sm text-gray-500">{c.current_title}{c.current_company?` at ${c.current_company}`:""}</div><div className="flex gap-4 mt-2 text-xs text-gray-400 flex-wrap">{c.email&&<span>{c.email}</span>}{c.phone&&<span>{c.phone}</span>}{(c.city||c.state)&&<span>{[c.city,c.state].filter(Boolean).join(", ")}</span>}{c.experience_years&&<span>{c.experience_years}yr exp</span>}</div></div></div></div>
<div className="flex border-b mb-4">{["overview","responses","ai"].map(t=><button key={t} onClick={()=>setTab(t)} className={`px-4 py-2 text-sm border-b-2 capitalize ${tab===t?"border-slate-800 text-slate-800":"border-transparent text-gray-400"}`}>{t==="ai"?"AI analysis":t}</button>)}</div>
{tab==="overview"&&<div className="grid md:grid-cols-2 gap-4">
<div className="bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-3">Contact</h3>{[["Email",c.email],["Phone",c.phone],["Location",[c.city,c.state].filter(Boolean).join(", ")]].map(([l,v])=>v?<div key={l as string} className="flex justify-between py-1 border-b border-gray-50 text-xs"><span className="text-gray-400">{l}</span><span>{v as string}</span></div>:null)}</div>
<div className="bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-3">Professional</h3>{[["Title",c.current_title],["Company",c.current_company],["Experience",c.experience_years?`${c.experience_years}yr`:null],["Source",c.source]].map(([l,v])=>v?<div key={l as string} className="flex justify-between py-1 border-b border-gray-50 text-xs"><span className="text-gray-400">{l}</span><span className="capitalize">{v as string}</span></div>:null)}</div>
{c.skills&&c.skills.length>0&&<div className="md:col-span-2 bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-2">Skills</h3><div className="flex flex-wrap gap-1">{c.skills.map(s=><span key={s} className="px-2 py-0.5 bg-blue-50 text-blue-700 rounded-full text-[10px]">{s}</span>)}</div></div>}
</div>}
{tab==="responses"&&<div className="space-y-4">
{c.screening_responses&&<div className="bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-3">Screening responses</h3>{typeof c.screening_responses==="object"?Object.entries(c.screening_responses).map(([k,v])=><div key={k} className="mb-3 p-3 bg-gray-50 rounded-lg"><div className="text-[10px] font-medium text-gray-400 mb-1">{k}</div><div className="text-sm">{String(v)}</div></div>):<p className="text-sm">{String(c.screening_responses)}</p>}</div>}
{c.application_answers&&<div className="bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-3">Application answers</h3>{typeof c.application_answers==="object"?Object.entries(c.application_answers).map(([k,v])=><div key={k} className="mb-3 p-3 bg-gray-50 rounded-lg"><div className="text-[10px] font-medium text-gray-400 mb-1">{k}</div><div className="text-sm">{String(v)}</div></div>):<p className="text-sm">{String(c.application_answers)}</p>}</div>}
{c.resume_text&&<div className="bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-3">Resume</h3><p className="text-xs whitespace-pre-wrap max-h-72 overflow-auto">{c.resume_text}</p></div>}
{!c.screening_responses&&!c.application_answers&&!c.resume_text&&<div className="bg-white rounded-xl border p-10 text-center text-gray-400 text-sm">No responses recorded.</div>}
</div>}
{tab==="ai"&&<div className="bg-white rounded-xl border p-6 text-center"><h3 className="font-medium mb-2">AI analysis</h3><p className="text-xs text-gray-400 mb-4">Coming soon - analyzes grammar, spelling, experience.</p></div>}
</div>;}

function Jobs(){
const[js,setJs]=useState<any[]>([]);const[cl,setCl]=useState<Record<string,string>>({});
useEffect(()=>{(async()=>{const{data:j}=await supabase.from("jobs").select("*").order("created_at",{ascending:false});const{data:c}=await supabase.from("clients").select("id,company_name");setJs(j||[]);setCl((c||[]).reduce((a:any,x:any)=>{a[x.id]=x.company_name;return a;},{}));})();},[]);
return<div><h1 className="text-xl font-semibold mb-4">Positions ({js.length})</h1><div className="space-y-2">{js.map(j=><div key={j.id} className="bg-white rounded-xl border p-4 flex justify-between items-center"><div><div className="font-medium">{j.title}</div><div className="text-xs text-gray-400 flex gap-3 mt-1">{cl[j.client_id]&&<span>{cl[j.client_id]}</span>}<span>{j.location||"Remote"}</span></div></div><B s={j.status}/></div>)}</div></div>;}

function Clients(){
const[cs,setCs]=useState<any[]>([]);
useEffect(()=>{supabase.from("clients").select("*").order("company_name").then(({data})=>setCs(data||[]));},[]);
return<div><h1 className="text-xl font-semibold mb-4">Clients ({cs.length})</h1><div className="space-y-2">{cs.map(c=><div key={c.id} className="bg-white rounded-xl border p-4 flex justify-between items-center"><div className="flex items-center gap-3"><Av n={c.company_name}/><div><div className="font-medium capitalize">{c.company_name}</div><div className="text-xs text-gray-400">{c.industry||""}</div></div></div><B s={c.status}/></div>)}</div></div>;}

function Careers(){
const[js,setJs]=useState<any[]>([]);
useEffect(()=>{supabase.from("jobs").select("*").eq("status","open").order("created_at",{ascending:false}).then(({data})=>setJs(data||[]));},[]);
return<div className="max-w-2xl mx-auto"><div className="text-center mb-8"><h1 className="text-2xl font-semibold">Open positions</h1></div><div className="space-y-3">{js.map(j=><div key={j.id} className="bg-white rounded-xl border p-5"><div className="font-medium">{j.title}</div><div className="text-xs text-gray-400 mt-1">{j.location||"Remote"}</div>{j.description&&<p className="text-xs text-gray-500 mt-3">{j.description.slice(0,200)}...</p>}</div>)}</div></div>;}

function Search({nav}:{nav:(p:string,d?:any)=>void}){
const[q,setQ]=useState("");const[rs,setRs]=useState<C[]>([]);
async function go(){if(!q.trim())return;const ws=q.toLowerCase().split(/\s+/).filter(w=>w.length>2);const or=ws.map(w=>`first_name.ilike.%${w}%,last_name.ilike.%${w}%,current_title.ilike.%${w}%`).join(",");const{data}=await supabase.from("candidates").select("*").or(or).limit(20);setRs(data||[]);}
return<div><h1 className="text-xl font-semibold mb-4">AI Search</h1><div className="flex gap-2 mb-4"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&go()} placeholder='Search candidates...' className="flex-1 px-3 py-2 border rounded-lg text-sm"/><button onClick={go} className="bg-slate-800 text-white px-4 py-2 rounded-lg text-sm">Search</button></div>{rs.length>0&&<div className="bg-white rounded-xl border divide-y">{rs.map(c=><div key={c.id} onClick={()=>nav("det",{id:c.id})} className="px-4 py-3 cursor-pointer hover:bg-gray-50 flex justify-between items-center"><div className="flex items-center gap-2"><Av n={`${c.first_name} ${c.last_name}`} sz="w-7 h-7 text-[10px]"/><div><div className="text-sm font-medium">{c.first_name} {c.last_name}</div><div className="text-[10px] text-gray-400">{c.current_title||""}</div></div></div><B s={c.status}/></div>)}</div>}</div>;}

const NV=[{id:"dash",l:"Dashboard",i:"\u{1F4CA}"},{id:"cands",l:"Candidates",i:"\u{1F465}"},{id:"jobs",l:"Positions",i:"\u{1F4BC}"},{id:"clients",l:"Clients",i:"\u{1F3E2}"},{id:"careers",l:"Careers",i:"\u{1F310}"},{id:"search",l:"AI Search",i:"\u{1F50D}"}];

export default function Home(){
const[pg,setPg]=useState("dash");const[pr,setPr]=useState<any>({});
const nav=useCallback((p:string,d:any={})=>{setPg(p);setPr(d);},[]);
const R=()=>{switch(pg){case"dash":return<Dash nav={nav}/>;case"cands":return<Cands nav={nav}/>;case"det":return<Det nav={nav} pr={pr}/>;case"jobs":return<Jobs/>;case"clients":return<Clients/>;case"careers":return<Careers/>;case"search":return<Search nav={nav}/>;default:return<Dash nav={nav}/>;}};
return<div className="flex min-h-screen"><aside className="w-48 bg-slate-900 flex flex-col shrink-0"><div className="p-4 border-b border-slate-700"><div className="text-sm font-semibold text-white">Streamlined</div><div className="text-[10px] text-slate-500">Staffing ATS</div></div><nav className="flex-1 p-2">{NV.map(it=>{const a=pg===it.id||(it.id==="cands"&&pg==="det");return<button key={it.id} onClick={()=>nav(it.id)} className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-sm text-left mb-0.5 ${a?"bg-slate-800 text-white":"text-slate-400 hover:text-slate-200"}`}><span>{it.i}</span>{it.l}</button>;})}</nav></aside><main className="flex-1 bg-gray-50 overflow-auto"><header className="bg-white border-b px-6 py-3 flex justify-between items-center"><span className="text-sm text-gray-400 capitalize">{pg}</span><Av n="Adam" sz="w-7 h-7 text-[10px]"/></header><div className="p-6 max-w-6xl mx-auto">{R()}</div></main></div>;}
