"use client";
import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/lib/auth";
import { B, Av, Modal, Field, TextArea, Select, logActivity, MediaLink, Empty, CAND_STATUSES, C, fn, useToast, Btn, Inline, Score, scoreText, ago, exportCsv, fullName } from "@/lib/ui";
import { callCandidate, smsCandidate } from "@/lib/comms";

const SOURCES = ["indeed", "linkedin", "onlinejobs", "olj", "apollo", "referral", "manual", "resume", "sheet", "careers", "search", "sourcing"];

/* ---------------- Candidates list ---------------- */
export function Cands({ nav, editable, pr }: { nav: (p: string, d?: any) => void; editable: boolean; pr?: any }) {
  const { profile } = useAuth(); const { say } = useToast();
  const [cs, setCs] = useState<C[]>([]); const [q, setQ] = useState(pr?.q || ""); const [f, setF] = useState(pr?.status || "all"); const [own, setOwn] = useState("all"); const [src, setSrc] = useState("all"); const [sort, setSort] = useState("created_at.desc"); const [pg, setPg] = useState(0); const [tot, setTot] = useState(0); const [add, setAdd] = useState(!!pr?.add); const [sel, setSel] = useState<Set<string>>(new Set()); const [bulkTag, setBulkTag] = useState(""); const [pools, setPools] = useState<any[]>([]); const [recs, setRecs] = useState<any[]>([]); const [imp, setImp] = useState(false); const [jobs, setJobs] = useState<any[]>([]); const [best, setBest] = useState<Record<string, any>>({}); const [loading, setLoading] = useState(true);
  const PAGE = 50;
  const recMap: Record<string, string> = {}; recs.forEach(r => { recMap[r.id] = r.first_name || r.email || "?"; });
  const load = useCallback(async () => {
    setLoading(true); let qr = supabase.from("candidates").select("id,first_name,last_name,email,phone,current_title,current_company,status,source,city,state,country,owner_id,created_at,updated_at,tags,overall_score,ai_recommendation,min_hourly_rate,experience_years", { count: "exact" });
    const term = q.trim(); if (term) qr = qr.or(`first_name.ilike.%${term}%,last_name.ilike.%${term}%,email.ilike.%${term}%,current_title.ilike.%${term}%,current_company.ilike.%${term}%,phone.ilike.%${term}%`);
    if (f !== "all") qr = qr.eq("status", f); if (src !== "all") qr = qr.ilike("source", `%${src}%`);
    if (own === "me" && profile) qr = qr.eq("owner_id", profile.id); else if (own === "unassigned") qr = qr.is("owner_id", null); else if (own !== "all") qr = qr.eq("owner_id", own);
    const [col, dir] = sort.split("."); const { data, count } = await qr.order(col, { ascending: dir === "asc", nullsFirst: false }).range(pg * PAGE, (pg + 1) * PAGE - 1);
    setCs(data || []); setTot(count || 0); setLoading(false);
    const ids = (data || []).map((c: any) => c.id); if (ids.length) { const { data: lb } = await supabase.from("v_job_leaderboard").select("candidate_id,job_id,score,rank,verdict").in("candidate_id", ids); const m: Record<string, any> = {}; (lb || []).forEach((r: any) => { if (!m[r.candidate_id] || (r.score || 0) > (m[r.candidate_id].score || 0)) m[r.candidate_id] = r; }); setBest(m); }
  }, [q, f, own, src, sort, pg, profile]);
  useEffect(() => { const t = setTimeout(load, q ? 250 : 0); return () => clearTimeout(t); }, [load, q]);
  useEffect(() => { supabase.from("profiles").select("id,first_name,last_name,email").in("role", ["super_admin", "admin", "recruiter", "hiring_manager"]).then(({ data }) => setRecs(data || [])); supabase.from("talent_pools").select("id,name").order("name").then(({ data }) => setPools(data || [])); supabase.from("jobs").select("id,title").in("status", ["open", "on_hold"]).order("created_at", { ascending: false }).then(({ data }) => setJobs(data || [])); }, []);
  const ids = () => Array.from(sel);
  function toggle(id: string) { setSel(p => { const n = new Set(p); n.has(id) ? n.delete(id) : n.add(id); return n; }); }
  async function bulkStatus(s: string) { if (!sel.size) return; await supabase.from("candidates").update({ status: s }).in("id", ids()); say(`${sel.size} set to ${s}.`); setSel(new Set()); load(); }
  async function bulkOwner(uid: string) { if (!sel.size) return; await supabase.from("candidates").update({ owner_id: uid || null }).in("id", ids()); say(`${sel.size} assigned.`); setSel(new Set()); load(); }
  async function applyBulkTag() { const t = bulkTag.trim(); if (!t || !sel.size) return; for (const c of cs.filter(x => sel.has(x.id))) { const tags = Array.from(new Set([...(((c as any).tags) || []), t])); await supabase.from("candidates").update({ tags }).eq("id", c.id); } setBulkTag(""); setSel(new Set()); load(); }
  async function applyBulkPool(poolId: string) { if (!poolId || !sel.size) return; const { data: ex } = await supabase.from("talent_pool_candidates").select("candidate_id").eq("talent_pool_id", poolId).in("candidate_id", ids()); const have = new Set((ex || []).map((x: any) => x.candidate_id)); const rows = ids().filter(id => !have.has(id)).map(cid => ({ talent_pool_id: poolId, candidate_id: cid })); if (rows.length) await supabase.from("talent_pool_candidates").insert(rows); setSel(new Set()); say(`${rows.length} added to pool.`); }
  async function applyBulkJob(jobId: string) { if (!jobId || !sel.size) return; const { data: st } = await supabase.from("pipeline_stages").select("id").order("sort_order").limit(1); const { data: ex } = await supabase.from("applications").select("candidate_id").eq("job_id", jobId).in("candidate_id", ids()); const have = new Set((ex || []).map((x: any) => x.candidate_id)); const rows = ids().filter(id => !have.has(id)).map(cid => ({ candidate_id: cid, job_id: jobId, stage_id: st?.[0]?.id || null, status: "active", source: "manual" })); if (rows.length) { const { error } = await supabase.from("applications").insert(rows); if (error) { say(error.message, false); return; } } setSel(new Set()); say(`${rows.length} added to job.`); }
  async function bulkDelete() { if (!sel.size) return; if (!confirm(`Permanently delete ${sel.size} candidate(s)? This cannot be undone.`)) return; const { error } = await supabase.from("candidates").delete().in("id", ids()); if (error) { say(error.message, false); return; } say(`${sel.size} deleted.`); setSel(new Set()); load(); }
  async function exportAll() { let qr = supabase.from("candidates").select("first_name,last_name,email,phone,current_title,current_company,status,source,city,state,country,skills,experience_years,min_hourly_rate,tags,created_at").limit(5000); if (f !== "all") qr = qr.eq("status", f); const { data } = await qr.order("created_at", { ascending: false }); exportCsv("candidates", data || []); }
  const SORTS = [["created_at.desc", "Newest"], ["created_at.asc", "Oldest"], ["updated_at.desc", "Recently updated"], ["last_name.asc", "Name A–Z"], ["overall_score.desc", "AI score"]];
  return <div>
    <div className="flex justify-between items-center mb-4 flex-wrap gap-2"><div><h1 className="text-xl font-semibold">Candidates <span className="text-gray-400 font-normal">({tot.toLocaleString()})</span></h1></div>{editable && <div className="flex gap-2"><Btn onClick={exportAll}>Export CSV</Btn><Btn onClick={() => setImp(true)}>✦ Import résumé</Btn><Btn primary onClick={() => setAdd(true)}>+ Add candidate</Btn></div>}</div>
    <div className="flex gap-2 mb-4 flex-wrap"><input value={q} onChange={e => { setQ(e.target.value); setPg(0); }} placeholder="Search name, email, phone, title, company…" className="flex-1 min-w-[220px] px-3 py-2 border rounded-lg text-sm" /><select value={f} onChange={e => { setF(e.target.value); setPg(0); }} className="px-3 py-2 border rounded-lg text-sm bg-white"><option value="all">All statuses</option>{CAND_STATUSES.map(s => <option key={s} value={s}>{s.replace(/_/g, " ")}</option>)}</select><select value={src} onChange={e => { setSrc(e.target.value); setPg(0); }} className="px-3 py-2 border rounded-lg text-sm bg-white"><option value="all">All sources</option>{SOURCES.map(s => <option key={s} value={s}>{s}</option>)}</select><select value={own} onChange={e => { setOwn(e.target.value); setPg(0); }} className="px-3 py-2 border rounded-lg text-sm bg-white"><option value="all">All recruiters</option><option value="me">Assigned to me</option><option value="unassigned">Unassigned</option>{recs.map(r => <option key={r.id} value={r.id}>{r.first_name || r.email}</option>)}</select><select value={sort} onChange={e => { setSort(e.target.value); setPg(0); }} className="px-3 py-2 border rounded-lg text-sm bg-white">{SORTS.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></div>
    {editable && sel.size > 0 && <div className="flex items-center gap-2 mb-3 p-2 bg-slate-800 rounded-lg text-white text-sm flex-wrap"><span className="px-2">{sel.size} selected</span><select onChange={e => { if (e.target.value) bulkStatus(e.target.value); e.target.value = ""; }} className="px-2 py-1 rounded text-slate-800 text-xs"><option value="">Set status…</option>{CAND_STATUSES.map(s => <option key={s} value={s}>{s.replace(/_/g, " ")}</option>)}</select><select onChange={e => { if (e.target.value) applyBulkJob(e.target.value); e.target.value = ""; }} className="px-2 py-1 rounded text-slate-800 text-xs"><option value="">Add to job…</option>{jobs.map(j => <option key={j.id} value={j.id}>{j.title}</option>)}</select><select onChange={e => { if (e.target.value) bulkOwner(e.target.value === "none" ? "" : e.target.value); e.target.value = ""; }} className="px-2 py-1 rounded text-slate-800 text-xs"><option value="">Assign to…</option><option value="none">Unassign</option>{recs.map(r => <option key={r.id} value={r.id}>{r.first_name || r.email}</option>)}</select><input value={bulkTag} onChange={e => setBulkTag(e.target.value)} onKeyDown={e => e.key === "Enter" && applyBulkTag()} placeholder="add tag…" className="px-2 py-1 rounded text-slate-800 text-xs w-28" /><button onClick={applyBulkTag} className="text-xs px-2 py-1 bg-white/20 rounded">Tag</button><select onChange={e => { if (e.target.value) applyBulkPool(e.target.value); e.target.value = ""; }} className="px-2 py-1 rounded text-slate-800 text-xs"><option value="">Add to pool…</option>{pools.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><button onClick={bulkDelete} className="text-xs px-2 py-1 text-red-300 hover:text-red-100">Delete</button><button onClick={() => setSel(new Set())} className="text-xs px-2 py-1 ml-auto">Clear</button></div>}
    <div className="bg-white rounded-xl border overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left bg-gray-50/60"><th className="px-3 py-2">{editable && <input type="checkbox" checked={sel.size > 0 && sel.size === cs.length} onChange={e => setSel(e.target.checked ? new Set(cs.map(c => c.id)) : new Set())} className="w-4 h-4" />}</th>{["Name", "Title", "Location", "Status", "AI", "Owner", "Source", "Added"].map((h, hi) => <th key={hi} className="px-3 py-2 text-[10px] font-semibold text-gray-400 uppercase whitespace-nowrap">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-50">{loading && cs.length === 0 ? <tr><td colSpan={9} className="p-8 text-center text-gray-400 text-xs">Loading…</td></tr> : cs.length === 0 ? <tr><td colSpan={9}><Empty /></td></tr> : cs.map(c => { const b = best[c.id]; return <tr key={c.id} className="hover:bg-gray-50"><td className="px-3 py-2" onClick={e => e.stopPropagation()}>{editable && <input type="checkbox" checked={sel.has(c.id)} onChange={() => toggle(c.id)} className="w-4 h-4" />}</td><td className="px-3 py-2 cursor-pointer" onClick={() => nav("det", { id: c.id })}><div className="flex items-center gap-2"><Av n={fullName(c)} sz="w-7 h-7 text-[9px]" /><div><div className="font-medium whitespace-nowrap">{fullName(c)}</div><div className="text-[10px] text-gray-400">{c.email || c.phone || ""}</div></div></div></td><td className="px-3 py-2 text-gray-500 max-w-[220px]"><div className="truncate">{c.current_title || ""}</div>{c.current_company && <div className="text-[10px] text-gray-400 truncate">{c.current_company}</div>}</td><td className="px-3 py-2 text-xs text-gray-500 whitespace-nowrap">{[c.city, c.state || c.country].filter(Boolean).join(", ")}</td><td className="px-3 py-2"><B s={c.status} /></td><td className="px-3 py-2 whitespace-nowrap">{b ? <span className={`text-xs font-bold ${scoreText(b.score)}`} title={`#${b.rank} · ${b.verdict}`}>{b.score}</span> : c.overall_score ? <span className={`text-xs font-bold ${scoreText(c.overall_score)}`}>{c.overall_score}</span> : <span className="text-gray-200">—</span>}</td><td className="px-3 py-2 text-[11px] text-gray-500">{c.owner_id && recMap[c.owner_id] ? recMap[c.owner_id] : <span className="text-gray-300">—</span>}</td><td className="px-3 py-2 text-gray-400 capitalize text-xs">{c.source || ""}</td><td className="px-3 py-2 text-[10px] text-gray-400 whitespace-nowrap">{ago(c.created_at)}</td></tr>; })}</tbody></table>
      <div className="flex justify-between px-3 py-2 border-t text-xs text-gray-400"><span>{tot ? pg * PAGE + 1 : 0}-{Math.min((pg + 1) * PAGE, tot)} of {tot.toLocaleString()}</span><div className="flex gap-1"><button disabled={pg === 0} onClick={() => setPg(p => p - 1)} className="px-2 py-1 border rounded disabled:opacity-30">Prev</button><button disabled={(pg + 1) * PAGE >= tot} onClick={() => setPg(p => p + 1)} className="px-2 py-1 border rounded disabled:opacity-30">Next</button></div></div></div>
    {add && <AddCandidate onClose={() => setAdd(false)} onSaved={(id) => { setAdd(false); if (id) nav("det", { id }); else load(); }} />}
    {imp && <ImportResume onClose={() => setImp(false)} onSaved={() => { setImp(false); load(); }} />}
  </div>;
}

export function ImportResume({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const [text, setText] = useState(""); const [p, setP] = useState<any>(null); const [busy, setBusy] = useState(false); const [err, setErr] = useState("");
  async function parse() { if (text.trim().length < 30) { setErr("Paste the résumé text first."); return; } setBusy(true); setErr(""); try { const d: any = await fn("ai-assist", { action: "parse", text }); setP(d.parsed || d || {}); } catch (e: any) { setErr("AI parse failed: " + (e?.message || e)); } setBusy(false); }
  async function save() { if (!p?.first_name) { setErr("No name parsed — edit the fields or try again."); return; } setBusy(true); const { error } = await supabase.from("candidates").insert({ first_name: p.first_name, last_name: p.last_name || "-", email: p.email || null, phone: p.phone || null, current_title: p.current_title || null, current_company: p.current_company || null, experience_years: p.experience_years || null, skills: Array.isArray(p.skills) ? p.skills : null, resume_text: text, status: "new", source: "resume" }); setBusy(false); if (error) setErr(error.message); else onSaved(); }
  return <Modal title="Import from résumé" onClose={onClose}>
    {!p ? <><TextArea label="Paste résumé text" value={text} onChange={(e: any) => setText(e.target.value)} rows={10} placeholder="Paste the full résumé here…" />{err && <p className="text-xs text-red-500 mb-2">{err}</p>}<Btn primary disabled={busy} onClick={parse} className="w-full">{busy ? "Parsing with AI…" : "✦ Parse with AI"}</Btn></>
      : <><div className="grid grid-cols-2 gap-2"><Field label="First name" value={p.first_name || ""} onChange={(e: any) => setP({ ...p, first_name: e.target.value })} /><Field label="Last name" value={p.last_name || ""} onChange={(e: any) => setP({ ...p, last_name: e.target.value })} /><Field label="Email" value={p.email || ""} onChange={(e: any) => setP({ ...p, email: e.target.value })} /><Field label="Phone" value={p.phone || ""} onChange={(e: any) => setP({ ...p, phone: e.target.value })} /><Field label="Title" value={p.current_title || ""} onChange={(e: any) => setP({ ...p, current_title: e.target.value })} /><Field label="Company" value={p.current_company || ""} onChange={(e: any) => setP({ ...p, current_company: e.target.value })} /></div>{p.skills?.length > 0 && <div className="mb-3 flex flex-wrap gap-1">{p.skills.map((s: string) => <span key={s} className="px-2 py-0.5 bg-blue-50 text-blue-700 rounded-full text-[10px]">{s}</span>)}</div>}{err && <p className="text-xs text-red-500 mb-2">{err}</p>}<Btn primary disabled={busy} onClick={save} className="w-full">{busy ? "Saving…" : "Save candidate"}</Btn></>}
  </Modal>;
}
export function AddCandidate({ onClose, onSaved }: { onClose: () => void; onSaved: (id?: string) => void }) {
  const [f, setF] = useState<any>({ first_name: "", last_name: "", email: "", phone: "", current_title: "", current_company: "", city: "", country: "", source: "manual" }); const [busy, setBusy] = useState(false); const [err, setErr] = useState("");
  async function save() { if (!f.first_name) { setErr("First name required"); return; } setBusy(true); const row: any = { ...f, status: "new" }; Object.keys(row).forEach(k => { if (row[k] === "") row[k] = null; }); const { data, error } = await supabase.from("candidates").insert(row).select("id").single(); setBusy(false); if (error) setErr(error.message); else onSaved(data?.id); }
  return <Modal title="Add candidate" onClose={onClose}><div className="grid grid-cols-2 gap-2"><Field label="First name *" value={f.first_name} onChange={(e: any) => setF({ ...f, first_name: e.target.value })} /><Field label="Last name" value={f.last_name} onChange={(e: any) => setF({ ...f, last_name: e.target.value })} /><Field label="Email" value={f.email} onChange={(e: any) => setF({ ...f, email: e.target.value })} /><Field label="Phone" value={f.phone} onChange={(e: any) => setF({ ...f, phone: e.target.value })} /><Field label="Current title" value={f.current_title} onChange={(e: any) => setF({ ...f, current_title: e.target.value })} /><Field label="Company" value={f.current_company} onChange={(e: any) => setF({ ...f, current_company: e.target.value })} /><Field label="City" value={f.city} onChange={(e: any) => setF({ ...f, city: e.target.value })} /><Field label="Country" value={f.country} onChange={(e: any) => setF({ ...f, country: e.target.value })} /></div><Select label="Source" value={f.source} onChange={(e: any) => setF({ ...f, source: e.target.value })} options={SOURCES} />{err && <p className="text-xs text-red-500 mb-2">{err}</p>}<Btn primary disabled={busy} onClick={save} className="w-full">{busy ? "Saving..." : "Save candidate"}</Btn></Modal>;
}

/* ---------------- Edit candidate (everything editable) ---------------- */
const EDIT_FIELDS: [string, string, string?][] = [["first_name", "First name"], ["last_name", "Last name"], ["email", "Email"], ["phone", "Phone"], ["current_title", "Current title"], ["current_company", "Company"], ["city", "City"], ["state", "State"], ["country", "Country"], ["experience_years", "Years experience", "number"], ["min_hourly_rate", "Min hourly rate ($)", "number"], ["english_rate", "English rating"], ["linkedin_url", "LinkedIn URL"], ["resume_url", "Résumé URL"], ["voice_recording_url", "Voice recording URL"], ["video_url", "Video URL"]];
export function EditCandidate({ c, onClose, onSaved }: { c: any; onClose: () => void; onSaved: () => void }) {
  const init: any = {}; EDIT_FIELDS.forEach(([k]) => { init[k] = c[k] ?? ""; }); init.skills = (c.skills || []).join(", "); init.status = c.status; init.source = c.source || ""; init.notes = c.notes || "";
  const [f, setF] = useState<any>(init); const [busy, setBusy] = useState(false); const [err, setErr] = useState("");
  async function save() { setBusy(true); setErr(""); const row: any = {}; EDIT_FIELDS.forEach(([k, , t]) => { const v = f[k]; row[k] = v === "" ? null : t === "number" ? Number(v) : v; }); row.skills = f.skills.split(",").map((s: string) => s.trim()).filter(Boolean); row.status = f.status; row.source = f.source || null; row.notes = f.notes || null; const { error } = await supabase.from("candidates").update(row).eq("id", c.id); setBusy(false); if (error) setErr(error.message); else onSaved(); }
  return <Modal title={`Edit — ${fullName(c)}`} onClose={onClose} wide><div className="grid md:grid-cols-3 gap-x-3">{EDIT_FIELDS.map(([k, l, t]) => <Field key={k} label={l} type={t || "text"} value={f[k]} onChange={(e: any) => setF({ ...f, [k]: e.target.value })} />)}<Select label="Status" value={f.status} onChange={(e: any) => setF({ ...f, status: e.target.value })} options={CAND_STATUSES} /><Field label="Source" value={f.source} onChange={(e: any) => setF({ ...f, source: e.target.value })} /></div><Field label="Skills (comma separated)" value={f.skills} onChange={(e: any) => setF({ ...f, skills: e.target.value })} /><TextArea label="Internal notes" rows={3} value={f.notes} onChange={(e: any) => setF({ ...f, notes: e.target.value })} />{err && <p className="text-xs text-red-500 mb-2">{err}</p>}<Btn primary disabled={busy} onClick={save} className="w-full">{busy ? "Saving…" : "Save changes"}</Btn></Modal>;
}

/* ---------------- Candidate detail ---------------- */
export function Det({ nav, pr, editable }: { nav: (p: string, d?: any) => void; pr: any; editable: boolean }) {
  const { profile } = useAuth(); const { say } = useToast();
  const [c, setC] = useState<any>(null); const [tab, setTab] = useState("overview"); const [apps, setApps] = useState<any[]>([]); const [notes, setNotes] = useState<any[]>([]); const [note, setNote] = useState(""); const [scoring, setScoring] = useState(false); const [tag, setTag] = useState(""); const [emailOpen, setEmailOpen] = useState(!!pr?.email); const [acts, setActs] = useState<any[]>([]); const [recruiters, setRecruiters] = useState<any[]>([]); const [jobsList, setJobsList] = useState<any[]>([]); const [stages, setStages] = useState<any[]>([]); const [addPipe, setAddPipe] = useState(false); const [screens, setScreens] = useState<any[]>([]); const [edit, setEdit] = useState(false); const [ivs, setIvs] = useState<any[]>([]); const [resume, setResume] = useState(""); const [editResume, setEditResume] = useState(false);
  useEffect(() => { supabase.from("profiles").select("id,first_name,last_name,email,role").in("role", ["super_admin", "admin", "recruiter", "hiring_manager"]).then(({ data }) => setRecruiters(data || [])); supabase.from("jobs").select("id,title,status").order("created_at", { ascending: false }).then(({ data }) => setJobsList(data || [])); supabase.from("pipeline_stages").select("id,name,sort_order").order("sort_order").then(({ data }) => setStages(data || [])); }, []);
  const load = useCallback(async () => {
    const [{ data }, { data: ap }, { data: nt }, { data: ac }, { data: sr }, { data: iv }] = await Promise.all([
      supabase.from("candidates").select("*").eq("id", pr.id).single(),
      supabase.from("applications").select("id,status,created_at,job_id,stage_id,offer_amount,offer_date,offer_accepted_at,offer_declined_at,submitted_to_client_at,client_decision,jobs(title)").eq("candidate_id", pr.id).order("created_at", { ascending: false }),
      supabase.from("notes").select("*").eq("candidate_id", pr.id).order("created_at", { ascending: false }),
      supabase.from("activities").select("*").eq("candidate_id", pr.id).order("created_at", { ascending: false }).limit(100),
      supabase.from("v_job_leaderboard").select("job_id,score,tier,verdict,recommended_action_text,summary,screened_at,rank").eq("candidate_id", pr.id).order("score", { ascending: false }),
      supabase.from("interviews").select("*").eq("candidate_id", pr.id).order("scheduled_at", { ascending: false }),
    ]);
    setC(data); setApps(ap || []); setNotes(nt || []); setActs(ac || []); setScreens(sr || []); setIvs(iv || []); setResume(data?.resume_text || "");
  }, [pr.id]);
  useEffect(() => { load(); }, [load]);
  async function patch(p: any, activity?: string) { if (!c) return; const { error } = await supabase.from("candidates").update(p).eq("id", c.id); if (error) { say(error.message, false); return; } setC({ ...c, ...p }); if (activity) logActivity("note", activity, { candidate_id: c.id }, profile?.id).then(load); }
  async function setStatus(s: string) { if (!c) return; const prev = c.status; await supabase.from("candidates").update({ status: s }).eq("id", c.id); setC({ ...c, status: s }); logActivity("stage_change", `Status: ${prev} → ${s}`, { candidate_id: c.id }, profile?.id).then(load); }
  async function addNote() { if (!note.trim()) return; await supabase.from("notes").insert({ candidate_id: pr.id, content: note, user_id: profile?.id }); await logActivity("note", note.slice(0, 140), { candidate_id: pr.id }, profile?.id); setNote(""); load(); }
  async function addTag() { const t = tag.trim(); if (!t || !c) return; const tags = Array.from(new Set([...(c.tags || []), t])); await supabase.from("candidates").update({ tags }).eq("id", c.id); setC({ ...c, tags }); setTag(""); }
  async function removeTag(t: string) { if (!c) return; const tags = (c.tags || []).filter((x: string) => x !== t); await supabase.from("candidates").update({ tags }).eq("id", c.id); setC({ ...c, tags }); }
  async function setOwner(uid: string) { if (!c) return; await supabase.from("candidates").update({ owner_id: uid || null }).eq("id", c.id); setC({ ...c, owner_id: uid || null }); const rn = recruiters.find(r => r.id === uid); logActivity("assigned", `Assigned to ${rn ? (rn.first_name || rn.email) : "—"}`, { candidate_id: c.id }, profile?.id).then(load); }
  async function addToPipeline(jobId: string) { if (!jobId || !c) return; if (apps.some(a => a.job_id === jobId && a.status !== "rejected")) { say("Already in that job's pipeline."); setAddPipe(false); return; } const stageId = stages[0]?.id || null; const { error } = await supabase.from("applications").insert({ candidate_id: c.id, job_id: jobId, stage_id: stageId, status: "active", source: "manual" }); if (error) { say(error.message, false); return; } await logActivity("application_received", `Added to ${jobsList.find(j => j.id === jobId)?.title || "job"} pipeline`, { candidate_id: c.id, job_id: jobId }, profile?.id); setAddPipe(false); load(); say("Added to pipeline."); }
  async function moveStage(appId: string, stageId: string) { const a = apps.find(x => x.id === appId); const to = stages.find(s => s.id === stageId)?.name; const from = stages.find(s => s.id === a?.stage_id)?.name; const { error } = await supabase.from("applications").update({ stage_id: stageId }).eq("id", appId); if (error) { say(error.message, false); return; } await logActivity("stage_change", `Stage: ${from || "—"} → ${to || "—"} (${a?.jobs?.title || "job"})`, { candidate_id: c.id, job_id: a?.job_id, application_id: appId }, profile?.id); load(); }
  async function removeApp(appId: string) { if (!confirm("Remove this candidate from the job pipeline?")) return; await supabase.from("applications").delete().eq("id", appId); load(); }
  async function enrichC() { if (!c) return; say("Enriching from Apollo…"); try { const r: any = await fn("apollo-enrich", { candidate_id: c.id }); say(r.matched ? ("Enriched" + (r.updated?.length ? ": " + r.updated.join(", ") : " — no new fields")) : "No Apollo match found."); load(); } catch (e: any) { say("Apollo: " + (e?.message || e), false); } }
  async function recordOffer(appId: string) { const amt = window.prompt("Offer amount (e.g. 5 or 1200):"); if (amt === null) return; await supabase.from("applications").update({ offer_amount: parseFloat(amt.replace(/[^0-9.]/g, "")) || null, offer_date: new Date().toISOString() }).eq("id", appId); if (c) await supabase.from("candidates").update({ status: "offered" }).eq("id", c.id); await logActivity("offer", `Offer extended${amt ? " ($" + amt + ")" : ""}`, { candidate_id: pr.id }, profile?.id); load(); }
  async function offerDecision(appId: string, accepted: boolean) { await supabase.from("applications").update(accepted ? { offer_accepted_at: new Date().toISOString() } : { offer_declined_at: new Date().toISOString() }).eq("id", appId); if (c) await supabase.from("candidates").update({ status: accepted ? "placed" : "rejected" }).eq("id", c.id); await logActivity("offer", accepted ? "Offer accepted" : "Offer declined", { candidate_id: pr.id }, profile?.id); load(); }
  async function runAI() { setScoring(true); try { await fn("candidate-ai-analysis", { candidate_id: pr.id }, { timeoutMs: 120000 }); await load(); } catch (e: any) { say("AI analysis failed: " + (e?.message || e), false); } setScoring(false); }
  async function screenFor(jobId: string) { if (!jobId) return; const j = jobsList.find(x => x.id === jobId); say(`Screening for ${j?.title}…`); try { await fn("screening-agent", { action: "screen", candidate_id: pr.id, job_id: jobId }, { timeoutMs: 180000 }); say("Screened."); load(); } catch (e: any) { say("Screening: " + (e?.message || e), false); } }
  async function del() { if (!confirm(`Permanently delete ${fullName(c)}? This cannot be undone.`)) return; const { error } = await supabase.from("candidates").delete().eq("id", c.id); if (error) { say(error.message, false); return; } say("Candidate deleted."); nav("cands"); }
  async function saveResume() { await patch({ resume_text: resume }); setEditResume(false); say("Résumé text saved."); }
  if (!c) return <div className="py-20 text-center text-gray-400">Loading...</div>;
  const tabs = editable ? ["overview", "responses", "notes", "timeline", "ai"] : ["overview", "responses", "timeline", "ai"];
  const ICON: Record<string, string> = { stage_change: "→", note: "✎", email: "✉", call: "☎", text: "💬", interview: "🗓", placement: "🤝", application_received: "📥", candidate_scored: "★", assigned: "👤", offer: "💰" };
  const openJobs = jobsList.filter(j => j.status === "open" || j.status === "on_hold");
  return <div>
    <button onClick={() => nav("cands")} className="text-sm text-gray-400 mb-3 block">&larr; Candidates</button>
    <div className="bg-white rounded-xl border p-5 mb-4"><div className="flex gap-4"><Av n={fullName(c)} sz="w-14 h-14 text-xl" /><div className="flex-1 min-w-0"><div className="flex items-center gap-3 mb-1 flex-wrap"><h1 className="text-lg font-semibold"><Inline editable={editable} value={c.first_name} onSave={v => patch({ first_name: v })} /> <Inline editable={editable} value={c.last_name} onSave={v => patch({ last_name: v })} /></h1><B s={c.status} />{c.ai_recommendation && <span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${c.ai_recommendation === "ADVANCE" ? "bg-green-100 text-green-700" : c.ai_recommendation === "REJECT" ? "bg-red-100 text-red-700" : "bg-yellow-100 text-yellow-700"}`}>{c.ai_recommendation}{c.overall_score ? ` ${c.overall_score}` : ""}</span>}</div>
      <div className="text-sm text-gray-500"><Inline editable={editable} value={c.current_title || ""} placeholder="Add title" onSave={v => patch({ current_title: v })} /> {c.current_company || editable ? <>at <Inline editable={editable} value={c.current_company || ""} placeholder="company" onSave={v => patch({ current_company: v })} /></> : null}</div>
      <div className="flex gap-4 mt-2 text-xs text-gray-500 flex-wrap"><span>✉ <Inline editable={editable} value={c.email || ""} placeholder="add email" onSave={v => patch({ email: v })} /></span><span>☎ <Inline editable={editable} value={c.phone || ""} placeholder="add phone" onSave={v => patch({ phone: v })} /></span><span>📍 <Inline editable={editable} value={c.city || ""} placeholder="city" onSave={v => patch({ city: v })} />, <Inline editable={editable} value={c.state || c.country || ""} placeholder="state/country" onSave={v => patch({ state: v })} /></span><span><Inline editable={editable} type="number" value={c.experience_years ?? ""} placeholder="?" onSave={v => patch({ experience_years: v })} /> yrs exp</span>{(c.min_hourly_rate || editable) && <span>$<Inline editable={editable} type="number" value={c.min_hourly_rate ?? ""} placeholder="?" onSave={v => patch({ min_hourly_rate: v })} />/h</span>}{c.linkedin_url && <a href={c.linkedin_url} target="_blank" rel="noreferrer" className="text-blue-600">LinkedIn ↗</a>}<span className="text-gray-300">via {c.source || "?"} · {ago(c.created_at)}</span></div></div>
      {editable && <div className="flex flex-col gap-2 self-start items-end shrink-0"><div className="flex gap-1.5"><select value={c.status} onChange={e => setStatus(e.target.value)} className="h-9 px-2 border rounded-lg text-xs bg-white">{CAND_STATUSES.map(s => <option key={s} value={s}>{s.replace(/_/g, " ")}</option>)}</select><select value={c.owner_id || ""} onChange={e => setOwner(e.target.value)} className="h-9 px-2 border rounded-lg text-xs bg-white"><option value="">Unassigned</option>{recruiters.map(r => <option key={r.id} value={r.id}>{r.first_name || r.email}</option>)}</select></div>
        <div className="flex gap-1.5 flex-wrap justify-end"><Btn small primary onClick={() => callCandidate(c, say, profile?.id)} title="Opens the lead in Close with the number copied; call logs to the timeline">☎ Call</Btn><Btn small onClick={() => smsCandidate(c, say, profile?.id)}>💬 Text</Btn><Btn small onClick={() => setEmailOpen(true)}>✉ Email</Btn><Btn small onClick={() => setAddPipe(true)}>+ Job</Btn><select onChange={e => { if (e.target.value) screenFor(e.target.value); e.target.value = ""; }} className="text-xs px-2 py-1.5 border rounded-lg bg-white"><option value="">✦ AI-screen for…</option>{openJobs.map(j => <option key={j.id} value={j.id}>{j.title}</option>)}</select><Btn small onClick={enrichC}>Enrich</Btn><Btn small onClick={() => setEdit(true)}>✎ Edit</Btn></div></div>}</div>
      <div className="flex items-center gap-1.5 flex-wrap mt-3 pt-3 border-t">{(c.tags || []).map((t: string) => <span key={t} className="px-2 py-0.5 bg-slate-100 text-slate-700 rounded-full text-[11px] flex items-center gap-1">{t}{editable && <button onClick={() => removeTag(t)} className="text-slate-400 hover:text-slate-700">×</button>}</span>)}{editable && <input value={tag} onChange={e => setTag(e.target.value)} onKeyDown={e => e.key === "Enter" && addTag()} placeholder="+ tag" className="text-[11px] px-2 py-0.5 border rounded-full w-20 focus:w-32 transition-all" />}</div></div>
    <div className="flex border-b mb-4">{tabs.map(t => <button key={t} onClick={() => setTab(t)} className={`px-4 py-2 text-sm border-b-2 capitalize ${tab === t ? "border-slate-800 text-slate-800 font-medium" : "border-transparent text-gray-400"}`}>{t === "ai" ? "AI analysis" : t === "responses" ? "Résumé & answers" : t}</button>)}</div>
    {tab === "overview" && <div className="grid md:grid-cols-2 gap-4">
      {screens.length > 0 && <div className="md:col-span-2 bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-2">AI screening ({screens.length})</h3><div className="divide-y divide-gray-50">{screens.map((r: any) => <div key={r.job_id} className="py-2 flex items-start gap-3"><Score s={r.score} /><div className="flex-1 min-w-0"><div className="flex items-center gap-2 flex-wrap"><span className="text-sm font-medium">{jobsList.find(j => j.id === r.job_id)?.title || "Job"}</span><span className={`text-[10px] px-1.5 py-0.5 rounded-full font-semibold ${r.verdict === "PASS" ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"}`}>{r.verdict}</span>{r.tier && <span className="text-[10px] text-gray-500">{r.tier}</span>}{r.rank && <span className="text-[10px] text-gray-400">#{r.rank}</span>}<span className="text-[10px] text-gray-300">{ago(r.screened_at)}</span></div><div className="text-xs text-gray-500 line-clamp-2" title={r.summary || ""}>{r.summary || r.recommended_action_text || ""}</div></div><button onClick={() => nav("job", { id: r.job_id, tab: "slate" })} className="text-xs text-blue-600 hover:underline shrink-0">Slate ↗</button></div>)}</div></div>}
      <div className="md:col-span-2 bg-white rounded-xl border p-4"><div className="flex justify-between items-center mb-2"><h3 className="text-sm font-medium">Jobs &amp; pipeline ({apps.length})</h3>{editable && <Btn small onClick={() => setAddPipe(true)}>+ Add to job</Btn>}</div>{apps.length === 0 ? <p className="text-xs text-gray-400">Not in any job pipeline yet.</p> : apps.map((a: any) => <div key={a.id} className="py-2 border-b border-gray-50"><div className="flex justify-between items-center gap-2 flex-wrap"><span onClick={() => nav("job", { id: a.job_id })} className="text-sm cursor-pointer hover:underline">{a.jobs?.title || "Job"}</span><div className="flex items-center gap-2">{a.status === "rejected" ? <B s="rejected" /> : editable ? <select value={a.stage_id || stages[0]?.id || ""} onChange={e => moveStage(a.id, e.target.value)} className="text-xs px-2 py-1 border rounded-lg bg-white">{stages.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select> : <span className="text-xs">{stages.find(s => s.id === a.stage_id)?.name || stages[0]?.name}</span>}{editable && <button onClick={() => removeApp(a.id)} className="text-gray-300 hover:text-red-500 text-xs">×</button>}</div></div><div className="flex items-center gap-2 mt-1.5 flex-wrap text-[10px]">{a.submitted_to_client_at && <span className="px-2 py-0.5 bg-cyan-50 text-cyan-700 rounded-full">submitted to client {ago(a.submitted_to_client_at)}{a.client_decision ? ` · client: ${a.client_decision}` : ""}</span>}{a.offer_accepted_at ? <span className="px-2 py-0.5 bg-green-100 text-green-700 rounded-full">Offer accepted{a.offer_amount ? ` · $${a.offer_amount}` : ""}</span> : a.offer_declined_at ? <span className="px-2 py-0.5 bg-red-100 text-red-700 rounded-full">Offer declined</span> : a.offer_date ? <><span className="px-2 py-0.5 bg-orange-100 text-orange-700 rounded-full">Offer out{a.offer_amount ? ` · $${a.offer_amount}` : ""}</span>{editable && <><button onClick={() => offerDecision(a.id, true)} className="px-2 py-0.5 border rounded-lg">Mark accepted</button><button onClick={() => offerDecision(a.id, false)} className="px-2 py-0.5 border rounded-lg">Declined</button></>}</> : (editable && a.status !== "rejected" && <button onClick={() => recordOffer(a.id)} className="px-2 py-0.5 border rounded-lg">Record offer</button>)}</div></div>)}</div>
      <div className="bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-3">Details</h3>{[["Email", c.email], ["Phone", c.phone], ["Location", [c.city, c.state, c.country].filter(Boolean).join(", ")], ["Title", c.current_title], ["Company", c.current_company], ["Experience", c.experience_years ? `${c.experience_years}yr` : null], ["Rate", c.min_hourly_rate ? `$${c.min_hourly_rate}/h` : null], ["English", c.english_rate], ["Adam rating", c.adam_rating], ["Roe rating", c.roe_rating], ["Source", c.source], ["Owner", recruiters.find(r => r.id === c.owner_id)?.first_name]].map(([l, v]) => v ? <div key={l as string} className="flex justify-between py-1 border-b border-gray-50 text-xs gap-3"><span className="text-gray-400 shrink-0">{l}</span><span className="text-right truncate">{String(v)}</span></div> : null)}</div>
      <div className="bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-2">Skills</h3>{c.skills && c.skills.length > 0 ? <div className="flex flex-wrap gap-1">{c.skills.map((s: string) => <span key={s} className="px-2 py-0.5 bg-blue-50 text-blue-700 rounded-full text-[10px]">{s}</span>)}</div> : <p className="text-xs text-gray-400">None yet{editable ? " — click Edit to add." : "."}</p>}{ivs.length > 0 && <><h3 className="text-sm font-medium mt-4 mb-2">Interviews ({ivs.length})</h3>{ivs.map(i => <div key={i.id} className="text-xs py-1 border-b border-gray-50 flex justify-between"><span>{(i.type || "").replace(/_/g, " ")} · {i.scheduled_at ? new Date(i.scheduled_at).toLocaleString([], { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "—"}</span><span className="text-gray-400">{i.status}{i.recommendation ? ` · ${i.recommendation.replace(/_/g, " ")}` : ""}</span></div>)}</>}</div>
      {(c.resume_url || c.voice_recording_url || c.video_url) && <div className="md:col-span-2 bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-3">Documents &amp; media</h3><div className="grid md:grid-cols-2 gap-x-6"><MediaLink label="Résumé" url={c.resume_url} /><MediaLink label="Voice / video recording" url={c.voice_recording_url} /><MediaLink label="Video" url={c.video_url} /></div></div>}
      {editable && <div className="md:col-span-2 flex justify-end"><Btn small danger onClick={del}>Delete candidate</Btn></div>}
    </div>}
    {tab === "responses" && <div className="space-y-4">
      {c.screening_responses && <div className="bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-3">Screening responses</h3>{typeof c.screening_responses === "object" ? Object.entries(c.screening_responses).map(([k, v]) => <div key={k} className="mb-3 p-3 bg-gray-50 rounded-lg"><div className="text-[10px] font-medium text-gray-400 mb-1">{k}</div><div className="text-sm whitespace-pre-wrap">{typeof v === "object" ? JSON.stringify(v) : String(v)}</div></div>) : <p className="text-sm">{String(c.screening_responses)}</p>}</div>}
      {c.application_answers && <div className="bg-white rounded-xl border p-4"><h3 className="text-sm font-medium mb-3">Application answers</h3>{typeof c.application_answers === "object" ? Object.entries(c.application_answers).map(([k, v]) => <div key={k} className="mb-3 p-3 bg-gray-50 rounded-lg"><div className="text-[10px] font-medium text-gray-400 mb-1">{k}</div><div className="text-sm whitespace-pre-wrap">{typeof v === "object" ? JSON.stringify(v) : String(v)}</div></div>) : <p className="text-sm">{String(c.application_answers)}</p>}</div>}
      <div className="bg-white rounded-xl border p-4"><div className="flex justify-between items-center mb-3"><h3 className="text-sm font-medium">Résumé text</h3>{editable && (editResume ? <div className="flex gap-1"><Btn small primary onClick={saveResume}>Save</Btn><Btn small onClick={() => { setEditResume(false); setResume(c.resume_text || ""); }}>Cancel</Btn></div> : <Btn small onClick={() => setEditResume(true)}>{c.resume_text ? "Edit" : "Paste résumé"}</Btn>)}</div>{editResume ? <textarea value={resume} onChange={e => setResume(e.target.value)} rows={18} className="w-full px-3 py-2 border rounded-lg text-xs font-mono" /> : c.resume_text ? <p className="text-xs whitespace-pre-wrap max-h-[28rem] overflow-auto">{c.resume_text}</p> : <p className="text-xs text-gray-400">No résumé text yet. The enrich job pulls it from the résumé URL automatically; or paste it here.</p>}</div>
    </div>}
    {tab === "notes" && <div className="bg-white rounded-xl border p-4"><div className="flex gap-2 mb-4"><input value={note} onChange={e => setNote(e.target.value)} onKeyDown={e => e.key === "Enter" && addNote()} placeholder="Add a note..." className="flex-1 px-3 py-2 border rounded-lg text-sm" /><Btn primary onClick={addNote}>Add</Btn></div>{c.notes && <div className="mb-3 p-3 bg-yellow-50 rounded-lg text-sm whitespace-pre-wrap"><div className="text-[10px] text-yellow-700 mb-1">Profile notes</div>{c.notes}</div>}{notes.length === 0 ? <p className="text-xs text-gray-400">No notes yet.</p> : notes.map(n => <div key={n.id} className="py-2 border-b border-gray-50"><div className="text-sm whitespace-pre-wrap">{n.content}</div><div className="text-[10px] text-gray-400 mt-0.5">{new Date(n.created_at).toLocaleString()}</div></div>)}</div>}
    {tab === "timeline" && <div className="bg-white rounded-xl border p-4">{acts.length === 0 ? <p className="text-xs text-gray-400">No activity yet. Status changes, notes, emails, calls, and placements will appear here.</p> : <div className="space-y-3">{acts.map(a => <div key={a.id} className="flex gap-3"><div className="w-7 h-7 rounded-full bg-gray-100 flex items-center justify-center text-xs shrink-0">{ICON[a.type] || "•"}</div><div className="flex-1 min-w-0"><div className="text-sm">{a.description || a.type}</div><div className="text-[10px] text-gray-400">{(a.type || "").replace(/_/g, " ")} · {new Date(a.created_at).toLocaleString()}</div></div></div>)}</div>}</div>}
    {tab === "ai" && (() => { const a: any = c.ai_analysis && typeof c.ai_analysis === "object" ? c.ai_analysis : null; return <div className="bg-white rounded-xl border p-6">{a ? <div>
      <div className="flex items-center gap-4 mb-4"><Score s={c.overall_score ?? a.score} big /><div><span className={`text-xs px-2 py-0.5 rounded-full font-semibold ${c.ai_recommendation === "ADVANCE" ? "bg-green-100 text-green-700" : c.ai_recommendation === "REJECT" ? "bg-red-100 text-red-700" : "bg-yellow-100 text-yellow-700"}`}>{c.ai_recommendation || a.recommendation}</span><div className="text-xs text-gray-400 mt-1">General AI assessment · score out of 100. Job-specific scores are on the Overview tab.</div></div></div>
      {a.summary && <p className="text-sm text-gray-700 mb-4">{a.summary}</p>}
      <div className="grid md:grid-cols-2 gap-4">{a.strengths?.length > 0 && <div><h4 className="text-xs font-semibold text-green-700 mb-1">Strengths</h4><ul className="list-disc ml-4 text-sm text-gray-600 space-y-0.5">{a.strengths.map((s: string, i: number) => <li key={i}>{s}</li>)}</ul></div>}{a.concerns?.length > 0 && <div><h4 className="text-xs font-semibold text-red-600 mb-1">Concerns</h4><ul className="list-disc ml-4 text-sm text-gray-600 space-y-0.5">{a.concerns.map((s: string, i: number) => <li key={i}>{s}</li>)}</ul></div>}</div>
      {editable && <button disabled={scoring} onClick={runAI} className="mt-4 text-xs text-blue-600 hover:underline disabled:opacity-50">{scoring ? "Re-analyzing..." : "Re-run analysis"}</button>}
    </div> : <div className="text-center"><p className="text-sm text-gray-500 mb-4">Run a general AI analysis (1&ndash;100 with Advance / Hold / Reject). For a job-specific score with evidence, use &ldquo;AI-screen for…&rdquo; above.</p>{editable && <Btn primary disabled={scoring} onClick={runAI}>{scoring ? "Analyzing..." : "Run AI analysis"}</Btn>}</div>}</div>; })()}
    {emailOpen && <EmailModal cand={c} onClose={() => { setEmailOpen(false); load(); }} />}
    {edit && <EditCandidate c={c} onClose={() => setEdit(false)} onSaved={() => { setEdit(false); load(); say("Saved."); }} />}
    {addPipe && <Modal title="Add to a job pipeline" onClose={() => setAddPipe(false)}><label className="block mb-3"><span className="text-xs text-gray-500">Job</span><select onChange={e => e.target.value && addToPipeline(e.target.value)} className="w-full px-3 py-2 border rounded-lg text-sm mt-1 bg-white"><option value="">— select a job —</option>{openJobs.map(j => <option key={j.id} value={j.id}>{j.title}</option>)}</select></label><p className="text-[11px] text-gray-400">Adds this candidate at the first stage. Move them along from the job&rsquo;s Pipeline tab or right here on the profile.</p></Modal>}
  </div>;
}

export function EmailModal({ cand, onClose }: { cand: any; onClose: () => void }) {
  const { profile } = useAuth();
  const [tmpls, setTmpls] = useState<any[]>([]); const [subject, setSubject] = useState(""); const [bodyHtml, setBodyHtml] = useState(""); const [busy, setBusy] = useState(false); const [msg, setMsg] = useState(""); const [drafting, setDrafting] = useState(false); const [to, setTo] = useState(cand.email || "");
  useEffect(() => { supabase.from("email_templates").select("*").then(({ data }) => setTmpls(data || [])); }, []);
  async function draftAI() { setDrafting(true); setMsg(""); try { const d: any = await fn("ai-assist", { action: "outreach", candidate_id: cand.id, role: cand.current_title }); setSubject(d.subject || subject); setBodyHtml(d.body || d.text || bodyHtml); } catch (e: any) { setMsg("AI draft failed: " + (e?.message || e)); } setDrafting(false); }
  function fill(t: any) { const repl = (s: string) => (s || "").replace(/{{candidate.firstName}}/g, cand.first_name || "").replace(/{{candidate.lastName}}/g, cand.last_name || "").replace(/{{user.firstName}}/g, profile?.first_name || "").replace(/{{user.lastName}}/g, profile?.last_name || "").replace(/{{job.title}}/g, cand.current_title || "the role"); setSubject(repl(t.subject)); setBodyHtml(repl(t.body_html)); }
  async function send() {
    if (!to.trim()) { setMsg("Add a recipient email."); return; } if (!subject.trim()) { setMsg("Add a subject."); return; }
    setBusy(true); setMsg(""); let status = "queued"; let err = "";
    try { await fn("resend-email", { to: to.trim(), subject, html: bodyHtml.replace(/\n/g, "<br/>"), text: bodyHtml, candidate_id: cand.id }); status = "sent"; } catch (e: any) { status = "failed"; err = String(e?.message || e); }
    await supabase.from("emails").insert({ candidate_id: cand.id, user_id: profile?.id, to_email: to.trim(), subject, body_html: bodyHtml, direction: "outbound", status, sent_at: status === "sent" ? new Date().toISOString() : null });
    await logActivity("email", `Email ${status}: ${subject}`, { candidate_id: cand.id }, profile?.id);
    setBusy(false);
    if (status === "sent") onClose(); else setMsg(`Not delivered (${err || "sender not configured"}). Saved to history. Fix: add RESEND_API_KEY + a verified sender in Supabase → Edge Functions → Secrets, or use the Gmail button.`);
  }
  const gmail = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(to)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(bodyHtml)}`;
  return <Modal title="Email candidate" onClose={onClose}>
    <div className="flex justify-between items-center mb-3"><span className="text-xs text-gray-400">To</span><button type="button" disabled={drafting} onClick={draftAI} className="text-xs text-blue-600 hover:underline disabled:opacity-50">{drafting ? "Drafting…" : "✨ Draft with AI"}</button></div>
    <Field label="" value={to} onChange={(e: any) => setTo(e.target.value)} placeholder="email@example.com" />
    <Select label="Template" onChange={(e: any) => { const t = tmpls.find(x => x.id === e.target.value); if (t) fill(t); }} options={[["", "— blank —"], ...tmpls.map(t => [t.id, t.name])]} />
    <Field label="Subject" value={subject} onChange={(e: any) => setSubject(e.target.value)} />
    <TextArea label="Message" value={bodyHtml} onChange={(e: any) => setBodyHtml(e.target.value)} rows={8} />
    {msg && <p className="text-xs text-amber-600 mb-2">{msg}</p>}
    <div className="flex gap-2"><Btn primary disabled={busy} onClick={send} className="flex-1">{busy ? "Sending..." : "Send"}</Btn><a href={gmail} target="_blank" rel="noreferrer" onClick={() => logActivity("email", `Email via Gmail: ${subject}`, { candidate_id: cand.id }, profile?.id)} className="text-sm px-3 py-2 border rounded-lg hover:bg-gray-50">Open in Gmail</a></div>
  </Modal>;
}
