"use client";
import { useState, useEffect, useCallback, useRef, useMemo } from "react";
import { supabase, SUPABASE_URL, SUPABASE_ANON_KEY } from "@/lib/supabase";
import { useAuth, can, canEdit, canManageUsers, ROLE_LABELS, Role, Section } from "@/lib/auth";
import { B, Av, Modal, Field, Empty, useToast, Btn, Inline, Select } from "@/lib/ui";

/* ---------------- Clients ---------------- */
export function Clients({ nav, editable }: { nav: (p: string, d?: any) => void; editable: boolean }) {
  const [cs, setCs] = useState<any[]>([]); const [add, setAdd] = useState(false);
  const load = useCallback(async () => { const { data } = await supabase.from("clients").select("*").order("company_name"); setCs(data || []); }, []);
  useEffect(() => { load(); }, [load]);
  return <div><div className="flex justify-between items-center mb-4"><h1 className="text-xl font-semibold">Clients ({cs.length})</h1>{editable && <button onClick={() => setAdd(true)} className="bg-slate-800 text-white px-3 py-1.5 rounded-lg text-sm">+ Add client</button>}</div><div className="space-y-2">{cs.map(c => <div key={c.id} onClick={() => nav("client", { id: c.id })} className="bg-white rounded-xl border p-4 flex justify-between items-center cursor-pointer hover:bg-gray-50"><div className="flex items-center gap-3"><Av n={c.company_name} /><div><div className="font-medium capitalize">{c.company_name}</div><div className="text-xs text-gray-400">{c.industry || ""}</div></div></div><B s={c.status} /></div>)}</div>{add && <AddClient onClose={() => setAdd(false)} onSaved={() => { setAdd(false); load(); }} />}</div>;
}
export function AddClient({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const [f, setF] = useState<any>({ company_name: "", industry: "", website: "" }); const [busy, setBusy] = useState(false); const [err, setErr] = useState("");
  async function save() { if (!f.company_name) { setErr("Company name required"); return; } setBusy(true); const { error } = await supabase.from("clients").insert({ ...f, status: "active" }); setBusy(false); if (error) setErr(error.message); else onSaved(); }
  return <Modal title="Add client" onClose={onClose}><Field label="Company name *" value={f.company_name} onChange={(e: any) => setF({ ...f, company_name: e.target.value })} /><Field label="Industry" value={f.industry} onChange={(e: any) => setF({ ...f, industry: e.target.value })} /><Field label="Website" value={f.website} onChange={(e: any) => setF({ ...f, website: e.target.value })} />{err && <p className="text-xs text-red-500 mb-2">{err}</p>}<button disabled={busy} onClick={save} className="w-full bg-slate-800 text-white py-2 rounded-lg text-sm">{busy ? "Saving..." : "Save client"}</button></Modal>;
}
export function ClientDetail({ nav, pr, editable }: { nav: (p: string, d?: any) => void; pr: any; editable: boolean }) {
  const [cl, setCl] = useState<any>(null); const [jobs, setJobs] = useState<any[]>([]); const [contacts, setContacts] = useState<any[]>([]); const [addC, setAddC] = useState(false);
  const { say } = useToast();
  const load = useCallback(async () => { const { data } = await supabase.from("clients").select("*").eq("id", pr.id).single(); setCl(data); const { data: j } = await supabase.from("jobs").select("id,title,status,location").eq("client_id", pr.id); setJobs(j || []); const { data: ct } = await supabase.from("client_contacts").select("*").eq("client_id", pr.id); setContacts(ct || []); }, [pr.id]);
  useEffect(() => { load(); }, [load]);
  async function patch(p: any) { const { error } = await supabase.from("clients").update(p).eq("id", cl.id); if (error) { say(error.message, false); return; } setCl({ ...cl, ...p }); }
  async function removeContact(id: string) { if (!confirm("Remove this contact?")) return; await supabase.from("client_contacts").delete().eq("id", id); load(); }
  async function del() { if (!confirm(`Delete client "${cl.company_name}"? Jobs stay but become unassigned.`)) return; await supabase.from("jobs").update({ client_id: null }).eq("client_id", cl.id); const { error } = await supabase.from("clients").delete().eq("id", cl.id); if (error) { say(error.message, false); return; } nav("clients"); }
  if (!cl) return <div className="py-20 text-center text-gray-400">Loading...</div>;
  return <div><button onClick={() => nav("clients")} className="text-sm text-gray-400 mb-4 block">&larr; Clients</button>
    <div className="bg-white rounded-xl border p-5 mb-4 flex justify-between items-start"><div className="flex items-center gap-3"><Av n={cl.company_name} sz="w-12 h-12 text-lg" /><div><h1 className="text-lg font-semibold capitalize"><Inline editable={editable} value={cl.company_name} onSave={v => patch({ company_name: v })} /></h1><div className="text-sm text-gray-500 flex gap-2 flex-wrap"><Inline editable={editable} value={cl.industry || ""} placeholder="industry" onSave={v => patch({ industry: v })} /><span>·</span><Inline editable={editable} value={cl.website || ""} placeholder="website" onSave={v => patch({ website: v })} /></div><div className="text-xs text-gray-400 mt-1 whitespace-pre-wrap"><Inline editable={editable} multiline value={cl.notes || ""} placeholder="Click to add notes about this client" onSave={v => patch({ notes: v })} /></div></div></div><div className="flex flex-col items-end gap-2">{editable ? <select value={cl.status || "active"} onChange={e => patch({ status: e.target.value })} className="px-2 py-1 border rounded-lg text-xs bg-white">{["prospect", "active", "on_hold", "churned"].map(s => <option key={s} value={s}>{s.replace(/_/g, " ")}</option>)}</select> : <B s={cl.status} />}{editable && <Btn small onClick={() => nav("jobs", { add: "1" })}>+ Job</Btn>}</div></div>
    <div className="grid md:grid-cols-2 gap-4">
      <div><h3 className="text-sm text-gray-500 mb-2">Positions ({jobs.length})</h3><div className="bg-white rounded-xl border divide-y">{jobs.length === 0 ? <p className="p-4 text-xs text-gray-400">None</p> : jobs.map(j => <div key={j.id} onClick={() => nav("job", { id: j.id })} className="flex justify-between items-center px-4 py-2.5 cursor-pointer hover:bg-gray-50"><div><div className="text-sm">{j.title}</div><div className="text-[10px] text-gray-400">{j.location || "Remote"}</div></div><B s={j.status} /></div>)}</div></div>
      <div><div className="flex justify-between items-center mb-2"><h3 className="text-sm text-gray-500">Contacts ({contacts.length})</h3>{editable && <button onClick={() => setAddC(true)} className="text-xs text-blue-600">+ Add</button>}</div><div className="bg-white rounded-xl border divide-y">{contacts.length === 0 ? <p className="p-4 text-xs text-gray-400">None</p> : contacts.map(ct => <div key={ct.id} className="px-4 py-2.5"><div className="text-sm">{ct.first_name} {ct.last_name}{ct.is_primary ? <span className="ml-2 text-[9px] px-1.5 py-0.5 bg-blue-50 text-blue-700 rounded-full">Primary</span> : ""}</div><div className="text-[10px] text-gray-400">{[ct.title, ct.email, ct.phone].filter(Boolean).join(" · ")}{editable && <button onClick={() => removeContact(ct.id)} className="ml-2 text-gray-300 hover:text-red-500">remove</button>}</div></div>)}</div></div>
    </div>
    {editable && <div className="flex justify-end mt-4"><Btn small danger onClick={del}>Delete client</Btn></div>}
    {addC && <AddContact clientId={pr.id} onClose={() => setAddC(false)} onSaved={() => { setAddC(false); load(); }} />}
  </div>;
}

export function AddContact({ clientId, onClose, onSaved }: { clientId: string; onClose: () => void; onSaved: () => void }) {
  const [f, setF] = useState<any>({ first_name: "", last_name: "", title: "", email: "", phone: "", is_primary: false }); const [busy, setBusy] = useState(false); const [err, setErr] = useState("");
  async function save() { if (!f.first_name) { setErr("First name required"); return; } setBusy(true); const { error } = await supabase.from("client_contacts").insert({ ...f, client_id: clientId }); setBusy(false); if (error) setErr(error.message); else onSaved(); }
  return <Modal title="Add contact" onClose={onClose}><Field label="First name *" value={f.first_name} onChange={(e: any) => setF({ ...f, first_name: e.target.value })} /><Field label="Last name" value={f.last_name} onChange={(e: any) => setF({ ...f, last_name: e.target.value })} /><Field label="Title (e.g. DON, Admin)" value={f.title} onChange={(e: any) => setF({ ...f, title: e.target.value })} /><Field label="Email" value={f.email} onChange={(e: any) => setF({ ...f, email: e.target.value })} /><Field label="Phone" value={f.phone} onChange={(e: any) => setF({ ...f, phone: e.target.value })} /><label className="flex items-center gap-2 mb-3 text-sm"><input type="checkbox" checked={f.is_primary} onChange={e => setF({ ...f, is_primary: e.target.checked })} />Primary contact</label>{err && <p className="text-xs text-red-500 mb-2">{err}</p>}<button disabled={busy} onClick={save} className="w-full bg-slate-800 text-white py-2 rounded-lg text-sm">{busy ? "Saving..." : "Save contact"}</button></Modal>;
}
